CREATE TABLE WEB(
URL varchar(200) NOT NULL,
NAME varchar(50) NOT NULL,
constraint UQ_WEB_NAME unique(NAME),
CONSTRAINT PK_WEB_URL PRIMARY KEY(URL)
);

CREATE TABLE HEADQUARTERS(
COUNTRY varchar(20) NOT NULL,
NUMEMPLOYEES NUMBER(15),
NUMSTORES NUMBER(15),
ADDRESSSTREET varchar2(50),
ADDRESSNUM varchar2(7),
ADDRESSFLOOR varchar2(4),
ACCOUNTNUMBER varchar2(24),
NAMEDIRECTOR varchar (50),
DIRECTORID NUMBER(15),
CONSTRAINT PK_HEADQUARTERS_COUNTRY PRIMARY KEY(country)
);

CREATE TABLE WAREHOUSES(
WAREHOUSEID NUMBER(10) NOT NULL,
NUMWAITERSWA NUMBER(15),
NUMEMPLOYEES NUMBER(15),
ADDRESS varchar(50),
CONSTRAINT UQ_WAREHOUSES_ADDRESS unique(ADDRESS),
CONSTRAINT PK_WAREHOUSES_WAREHOUSEID PRIMARY KEY (WAREHOUSEID)
);

CREATE TABLE CUSTOMERS(
CUSTOMERID NUMBER(10) NOT NULL,
NAME varchar2(20) NOT NULL,
FIRSTNAME varchar2(20),
SECONDNAME varchar2(20),
CONSTRAINT PK_CUSTOMERS_CUSTOMERID PRIMARY KEY(CUSTOMERID)
);

CREATE TABLE PHYSICALS(
CUSTOMERID NUMBER(10) NOT NULL,
PHYSICALID NUMBER(10) NOT NULL,
TICKETID NUMBER(15),
CONSTRAINT UQ_PHYSICALS_TICKETID unique (TICKETID),
CONSTRAINT FK_PHYSICALS_CUSTOMERID foreign key (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID),
CONSTRAINT PK_PHYSICALS_CUSTOMERID PRIMARY KEY(CUSTOMERID)
);

CREATE TABLE EMPLOYEES(
EMPLOYEEID number(10) NOT NULL,
DNI char(9) null,
EMAIL varchar2(50) null,
ADDREESSSTRET varchar2(50),
ADRESSNUM varchar2(7),
ADRESSFLOOR varchar2(4),
ACOUNTNUMBER varchar2(24),
BIRTHDAY date not null,
AGE number(3),
NAME varchar2(20) not null,
FIRSTNAME varchar2(20),
SECONDNAME varchar2(20),
constraint UQ_EMPLYEES_DNI unique(DNI),
constraint UQ_EMPLOYEES_EMAIL unique(EMAIL),
constraint PK_EMPLOYEES_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)
);

CREATE TABLE COMPUTERENGENIEER (
EMPLOYEEID number(10) not null,
COMPUTERENID NUMBER(10) NOT NULL,
CONSTRAINT FK_COMPUNEER_EMPLOYEESID foreign key (COMPUTERENID) references EMPLOYEES(EMPLOYEEID),     
CONSTRAINT PK_COMPUTEER_COMPUID PRIMARY KEY(EMPLOYEEID)
) ;

CREATE TABLE EMPLOYEESEMAIL(
EMPLOYEEID NUMBER(10) not null,
EMAILS varchar2(50),
CONSTRAINT FK_EMPLOYEES_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_EMPLOYEESEMAIL_EMP_EMAIL PRIMARY KEY (EMPLOYEEID,EMAILS)
);

CREATE TABLE SELLERS(
EMPLOYEEID NUMBER (10) NOT NULL,
SELLERSID NUMBER(10) NOT NULL,
SHOPID NUMBER(10) NOT NULL,
CONSTRAINT FK_SELLERS_EMPLOYEEID foreign key (SELLERSID) references
EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_SELLERS_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)
) ;

CREATE TABLE CARRIERS (
EMPLOYEEID number(10) NOT NULL,
CARRIERSID NUMBER(10) NOT NULL,
PHONE NUMBER(20) NOT NULL,
constraint UQ_CARRIERS_PHONE unique (PHONE),
CONSTRAINT FK_CARRIERS_EMPLOYEEID foreign key (EMPLOYEEID) references
EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_CARRIERS_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)
) ;


CREATE TABLE SALARIES(
QUANTITY NUMBER (10) NOT NULL,
EMPLOYEEID NUMBER(10) NOT NULL,
EXTRAPAYMENTS NUMBER (10),
CONSTRAINT FK_SALARY_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES (EMPLOYEEID),
CONSTRAINT PK_SALARIES_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)

);

CREATE TABLE CLAIMS(
CLAIMCODE NUMBER(10) NOT NULL,
CUSTOMERID NUMBER(10) NOT NULL,
DAT NUMBER(10) NOT NULL,
EMPLOYEEATTENDS NUMBER (10),
NAMES varchar2(50),
DESCRIPT varchar2(50),
CONSTRAINT FK_CLAIMS_CUSTOMERID foreign key (CUSTOMERID) references CUSTOMERS (CUSTOMERID),
CONSTRAINT PK_CLAIMS_CUSTOMERID PRIMARY KEY(CUSTOMERID)
);

CREATE TABLE WAITERSWAREHOUSES (
EMPLOYEEID number(10) not null,
WAITERSID NUMBER(10) NOT NULL,
BEEPER NUMBER(10),
CONSTRAINT FK_WAITERS_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_WAITERS_EMPLOYEEID PRIMARY KEY (EMPLOYEEID)
) ;

CREATE TABLE MANAGERS (
EMPLOYEEID number(10) not null,
MANAGERID NUMBER(10) NOT NULL,
CONSTRAINT FK_MANAGERS_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_MANAGERS_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)

);

CREATE TABLE MANAGERSSTUDIES(
EMPLOYEEID NUMBER(10) not null,
QUALIFICATION NUMBER(3) not null,
CONSTRAINT FK_MANAGERS_MANAGERID foreign key (EMPLOYEEID) references MANAGERS (EMPLOYEEID),
CONSTRAINT PK_MANAGERSSTUDIES_MAN_STU PRIMARY KEY (EMPLOYEEID, QUALIFICATION)
);

CREATE TABLE DIRECTORS (
EMPLOYEEID number(10) not null,
DIRECTORID NUMBER(10) NOT NULL,
COMPANYID NUMBER(20) NOT NULL,
CONSTRAINT FK_DIRECTORS_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_DIRECTORS_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)
) ;

CREATE TABLE DIRECTORSSTUDIES(
EMPLOYEEID NUMBER(10)NOT NULL,
DIRECTORID NUMBER(10) not null,
QUALIFICATION NUMBER(10) NOT NULL,
CONSTRAINT FK_DIRECTORS_DIRECTORID foreign key (DIRECTORID) references DIRECTORS (EMPLOYEEID),
CONSTRAINT PK_DIRECTORSSTUDIES_DIRTU PRIMARY KEY (EMPLOYEEID, QUALIFICATION)
);

CREATE TABLE ADMINISTRATIVES (
EMPLOYEEID number(10) not null,
ADMINISTRATIVESID NUMBER(10) NOT NULL,
LICENSE NUMBER (20) NOT NULL,
CONSTRAINT FK_ADMINISTRATIVES_EMPLOYEEID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),
CONSTRAINT PK_ADMINISTRATIVES_EMPLOYEEID PRIMARY KEY (EMPLOYEEID)
) ;

CREATE TABLE CYBERS(
CUSTOMERID NUMBER(10,0) NOT NULL,
CYBERID NUMBER(10) NOT NULL,
URL varchar(200) not null,
ADDRESSSTREET varchar2(50),
ADDRESSNUM varchar2(7),
ADDRESSFLOOR varchar2(4),
ACCOUNTNUMBER varchar2(24),
CONSTRAINT FK_CYBERS_CUSTOMERID foreign key (CUSTOMERID) references CUSTOMERS (CUSTOMERID),
CONSTRAINT FK_CYBERS_URL foreign key (URL) references WEB (URL),
constraint PK_CYBERS_CUSTOMERID PRIMARY KEY(CUSTOMERID)
);

CREATE TABLE STORES(
STOREID NUMBER(10) NOT NULL,
CUSTOMERID NUMBER(10) NOT NULL,
COUNTRY varchar(20) NOT NULL,
ADDRESS varchar2(50),
NUMDEPARTMNETS NUMBER(15),
NUMEMPLOYEES NUMBER(15),
CONSTRAINT FK_STORES_CUSTOMERID foreign key (CUSTOMERID) references CUSTOMERS (CUSTOMERID),
CONSTRAINT FK_STORES_COUNTRY foreign key (COUNTRY) references HEADQUARTERS (COUNTRY),
CONSTRAINT UQ_STORES_ADDRESS unique (ADDRESS),
CONSTRAINT PK_STORES_STOREID PRIMARY KEY (STOREID)
);

CREATE TABLE STORETLPNUMBERS(
STOREID NUMBER(9) not null,
TLPNUMBER NUMBER(20),
CONSTRAINT FK_STORETLPNUMBERS_STOREID foreign key (STOREID) references STORES(STOREID),
CONSTRAINT PK_STORETLPNUMBERS_STO_TLPN PRIMARY KEY (STOREID,TLPNUMBER)
);

CREATE TABLE DEPARTMENTS(
DEPARTMENTID NUMBER(10) NOT NULL,
STOREID NUMBER(10) NOT NULL,
NUMDEPRODUCTS NUMBER(15),
NUMEMPLOYEES NUMBER(15),
CONSTRAINT FK_DEPARTMENTS_STOREID foreign key (STOREID) references STORES (STOREID),
CONSTRAINT PK_DEPARTMETNS_DEPARTMENTID PRIMARY KEY (DEPARTMENTID)

);

CREATE TABLE PRODUCTS(
PRODUCTID NUMBER(10) NOT NULL,
EMPLOYEEID NUMBER(10) NOT NULL,
DEPARTMENTID NUMBER(10) NOT NULL,
MODEL NUMBER(15),
COLOUR varchar(10),
CONSTRAINT FK_PRODUCTS_SELLERS foreign key (EMPLOYEEID) references SELLERS (EMPLOYEEID),
CONSTRAINT FK_PRODUCTS_DEPARTMENTID foreign key (DEPARTMENTID) references DEPARTMENTS (DEPARTMENTID),
CONSTRAINT PK_PRODUCTS_PRODUCTID PRIMARY KEY (PRODUCTID)
);

CREATE TABLE TRANSPORTCOMPANIES(
SHIPMENTID NUMBER(20) NOT NULL,
MODEOFTRANSPORT varchar2(20),
COST NUMBER (30),
DESTINATION varchar2(50),
CONSTRAINT PK_TRANSPORTNIES_SHIPMENTID PRIMARY KEY(SHIPMENTID)
);

CREATE TABLE STOWAR(
WAREHOUSEID NUMBER(10) NOT NULL,
STOREID NUMBER(10) NOT NULL,
CONSTRAINT FK_STOWAR_WAREHOUDEID FOREIGN KEY (WAREHOUSEID) REFERENCES WAREHOUSES (WAREHOUSEID),
CONSTRAINT FK_STOWAR_STOREID FOREIGN KEY (STOREID) REFERENCES STORES (STOREID),
CONSTRAINT PK_STOWAR_STOREID PRIMARY KEY (WAREHOUSEID,STOREID)
);

CREATE TABLE PROWAR(
WAREHOUSEID NUMBER(10) NOT NULL,
PRODUCTID NUMBER(10) NOT NULL,
CONSTRAINT FK_WAREHOUSES_WAREHOUSEID FOREIGN KEY (WAREHOUSEID) REFERENCES WAREHOUSES(WAREHOUSEID),
CONSTRAINT FK_PROWAR_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID),
CONSTRAINT PK_PROWAR_ID PRIMARY KEY (WAREHOUSEID,PRODUCTID)
);

CREATE TABLE DEPPHY(
CUSTOMERID NUMBER(10) NOT NULL,
DEPARTMENTID NUMBER(10) NOT NULL,
CONSTRAINT PK_DEPPHY_DEPARTMENTID FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID),
CONSTRAINT PK_DEPPHY_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID),
CONSTRAINT PK_DEPPHY_ID PRIMARY KEY (CUSTOMERID,DEPARTMENTID)
);

CREATE TABLE DEPDEP(
DEPARTMENTID NUMBER(10) NOT NULL,
EMPLOYEEID NUMBER(10) NOT NULL,
CONSTRAINT FK_DEPDEP_SELLERS FOREIGN KEY (EMPLOYEEID) REFERENCES SELLERS(EMPLOYEEID),
CONSTRAINT FK_DEPDEP_DEPARTMENTID FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID),
CONSTRAINT PK_DEPDEP_ID PRIMARY KEY (DEPARTMENTID,EMPLOYEEID)
);

CREATE TABLE SALES(
CUSTOMERID NUMBER(10) NOT NULL,
PRODUCTID NUMBER(10) NOT NULL,
STOREID NUMBER(10) NOT NULL,
CONSTRAINT FK_SALES_STOREID FOREIGN KEY (STOREID) REFERENCES STORES(STOREID),
CONSTRAINT FK_SALES_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID),
CONSTRAINT FK_SALES_PRODUCTID FOREIGN KEY(PRODUCTID) REFERENCES PRODUCTS(PRODUCTID),
CONSTRAINT PK_SALES_ID PRIMARY KEY (STOREID,CUSTOMERID,PRODUCTID)
);

CREATE TABLE SHOWCASES(
STOREID NUMBER(10) NOT NULL,
EMPLOYEEID NUMBER(10) NOT NULL,
SEASON varchar(20),
WEATHER varchar(20),
CONSTRAINT FK_SHOWCASES_SELLERSID foreign key (EMPLOYEEID) references SELLERS (EMPLOYEEID),
CONSTRAINT FK_SHOWCASES_STOREID foreign key (STOREID) references STORES (STOREID),
CONSTRAINT PK_SHOWCASES_STOREID PRIMARY KEY(STOREID,EMPLOYEEID)
);

CREATE TABLE ADVISORS (
EMPLOYEEID number(10) not null,
ADVISORSID NUMBER(10) NOT NULL,
DEPARTMENTID NUMBER(10) NOT NULL,
SEARCHNUMBER NUMBER(10) NOT NULL,
CONSTRAINT FK_ADVISORS_EMPLOYEESID foreign key (EMPLOYEEID) references EMPLOYEES(EMPLOYEEID),     
CONSTRAINT FK_ADVISORS_DEPARTMENTID foreign key (DEPARTMENTID) references DEPARTMENTS(DEPARTMENTID),
CONSTRAINT PK_ADVISORS_EMPLOYEEID PRIMARY KEY(EMPLOYEEID)
) ;
